### ISSUE TITLE
Asking for getting electric current data by the SDK of Multiclamp 700A

### ISSUE THREAD

**Issue by epiphanyKANG** [romainbrette/holypipette#104]
I am a user of the Multiclamp 700B and Digidata 1550B.
![image](https://user-images.githubusercontent.com/98371366/196609127-7e04b6a3-ac9f-47ff-9343-b7459e6a457e.png)

I have some trouble when I want to get the electric current data by the SDK (AxMultiClampMsg). Actually, I have realised the function of setting holding voltage (MCCMSG_SetHolding), but there is no guidance about getting the electric current data.

It would be appreciated if you could help to solve this problem.

I am looking forward to receiving your reply.

**Comment by romainbrette** [comment]
Sorry but that's a question for Molecular Device support!
We use a National Instruments board to acquire signals.
