### ISSUE TITLE
Can't run the new scripts on my Mac

### ISSUE THREAD

**Issue by romainbrette** [romainbrette/holypipette#44]
I get this error: "This application failed to start because it could not find or load the Qt platform plugin "cocoa"."
It seems to be some path problem (?), but what is weird is I didn't get that error before.
I know where the library is but I don't know who to tell it to!

**Comment by mstimberg** [comment]
Did you install Qt/PyQT via anaconda? It might just be a version mismatch, Could you run
```
conda update qt pyqt
```
?

**Comment by romainbrette** [comment]
I just did, but same problem!

**Comment by romainbrette** [comment]
Solution: add environment variable for the plugin path. On my computer:
QT_QPA_PLATFORM_PLUGIN_PATH=/Users/Romain/anaconda/envs/holypipette/lib/qt5/plugins/platforms
