### ISSUE TITLE
Separate patch and paramecium gui

### ISSUE THREAD

**Issue by romainbrette** [romainbrette/holypipette#52]
These two appear to be mixed. There's currently patch_gui and patch_gui_with_tracking. It should be patch_gui and paramecium_gui. There should be nothing about paramecium in the patch-clamp interface, and conversely.

**Comment by romainbrette** [comment]
Actually patch_gui_with_tracking is not paramecium but cell tracking. So we just need an extra file.

**Comment by romainbrette** [comment]
I have just created a ParameciumGui that replicates ManipulatorGui for the moment.

**Comment by mstimberg** [comment]
The GUIs are separated, but the advanced functionality for the ParameciumGUI (tracking, etc.) is currently broken.
