### ISSUE TITLE
Can't access github!

### ISSUE THREAD

**Issue by romainbrette** [romainbrette/holypipette#73]
On the experimental PC, the github is not accessible... ??? I checked that internet works and even github, but not holypipette! Has it become private?

**Comment by mstimberg** [comment]
I think this is just a temporary problem with the github servers. I can access it fine, and it is still public. But I had issues with github repositories this morning as well, and they are currently "investigating reports of elevated error rates" (https://status.github.com/messages).

**Comment by romainbrette** [comment]
ah ok good
